crate_name = "arbitrary"
version = "1.1.6"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
reasonably_maintained = true
has_unsafe_code = true
implements_crypto = false
dev_dependency_only = false
