crate_name = "assert_matches"
version = "1.5.0"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
testing_status = 2
has_unsafe_code = false
build_script = false
proc_macro = false
implements_crypto = false
