crate_name = "async-stream-impl"
version = "0.3.3"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
has_unsafe = true
maintainable_code = true
implements_crypto = false
dev_dependency_only = false
