crate_name = "atomic-polyfill"
version = "0.1.11"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
# Much like critical-section, atomic-polyfill uses unsafe to implement unsafe
# traits and e.g., manipulate UnsafeCells
has_unsafe_code = true
implements_crypto = false
