crate_name = "bindgen"
version = "0.60.1"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
reasonably_maintained = true
has_unsafe_code = true
build_script = true
proc_macro = true
unsafe_code_is_sound = true
implements_crypto = false
dev_dependency_only = false

[common.build_script_details]
deterministic = true
is_cross_compile_clean = true
syscall_types_used = ["file operations"]

[common.build_script_details.purpose]
codegen = false
cfg_algebra = false
links_libs = []
builds_libs = []
misc = false

[common.proc_macro_details]
deterministic = true
is_cross_compile_clean = true
