crate_name = "bytes"
version = "0.5.6"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
has_unsafe_code = true
implements_crypto = false
maintainable_code = 2
good_api = true
good_docs = true
