crate_name = "capnp"
version = "0.14.11"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
# Reader/Writer unsafe implementations had huge unsafe blocks. This also uses
# quite a few unsafe ops for forming slices from raw pointers, writing directly
# to pointers, etc.
has_unsafe_code = true
implements_crypto = false
