crate_name = "critical-section"
version = "1.1.1"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
# critical-section makes reasonable use of unsafe to emphasize the inherent
# racey-ness of its operations.
has_unsafe_code = true
implements_crypto = false
