crate_name = "document-features"
version = "0.2.6"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
maintainable_code = 2
proc_macro = true
has_unsafe = false
dev_dependency_only = false

[common.proc_macro_details]
# The macro will parse the Cargo.toml file to generate documentation.
deterministic = false
is_cross_compile_clean = true
