crate_name = "euclid"
version = "0.22.7"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true

# The only unsafe usage is in bytemuck::Zeroable impls, which appear to follow the safety rules.
has_unsafe_code = true
unsafe_code_is_sound = true
