crate_name = "hex"
version = "0.4.3"
reviewed-by-team = "ChromeOS"
[common]
code_is_not_malicious = true
has_unsafe_code = false
implements_crypto = false
deterministic = true
is_cross_compile_clean = true
