crate_name = "nix"
version = "0.24.2"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
has_unsafe_code = true
build_script = false
proc_macro = false
implements_crypto = false
reasonably_maintained = true
good_docs = true
