crate_name = "petgraph"
version = "0.6.2"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
implements_crypto = false
has_unsafe = true
maintainable_code = true
dev_dependency_only = false

