crate_name = "prost-types"
version = "0.11.1"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
implements_crypto = false
has_unsafe = false
maintainable_code = true
dev_dependency_only = false

