crate_name = "rustyline-derive"
version = "0.6.0"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
reasonably_maintained = true
has_unsafe_code = false
implements_crypto = false
dev_dependency_only = false
