crate_name = "syn"
version = "1.0.80"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
has_unsafe_code = true
maintainable_code = 2
good_api = true
good_docs = true
build_script = true
proc_macro = true
