crate_name = "tonic-build"
version = "0.8.2"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
implements_crypto = false
has_unsafe = false
maintainable_code = true
dev_dependency_only = false

