crate_name = "userfaultfd-sys"
version = "0.4.2"
reviewed-by-team = "ChromeOS"
features = [ "default", "linux4_14", "linux5_7" ]

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = false
testing_status = 0
reasonably_maintained = false
has_unsafe_code = false
build_script = true
proc_macro = false
implements_crypto = false
dev_dependency_only = false

[common.build_script_details]
deterministic = true
is_cross_compile_clean = false
syscall_types_used = ["file operations"]

[common.build_script_details.purpose]
codegen = true
cfg_algebra = true
links_libs = []
builds_libs = []
misc = false
