crate_name = "userfaultfd"
version = "0.5.0"
reviewed-by-team = "ChromeOS"
features = [ "default", "linux4_14", "linux5_7" ]

[common]
code_is_not_malicious = true
maintainable_code = 2
good_api = true
good_docs = true
testing_status = 2
reasonably_maintained = false
has_unsafe_code = true
build_script = false
proc_macro = false
unsafe_code_is_sound = true
implements_crypto = false
dev_dependency_only = false
