crate_name = "zerocopy"
version = "0.7.0-alpha.1"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
has_unsafe = true
maintainable_code = true
implements_crypto = false
dev_dependency_only = false
