crate_name = "zerocopy-derive"
version = "0.3.2"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
has_unsafe = true
maintainable_code = true
implements_crypto = false
dev_dependency_only = false
