[package]
name = "ippusb_bridge"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
chunked_transfer = "1"
getopts = "0.2.18"
httparse = "1.3.4"
libc = "0.2.44"
rusb = "0.8.1"
tiny_http = "0.8.0"
